version: '3'
services:
  frontend:
      image: coltonpalfrey/aivaluate-frontend:dev
      container_name: frontend
      ports:
        - "5173:5173"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: database
    environment:
      POSTGRES_DB: AIvaluatedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

# A database manager can be accessed at http://localhost:8080/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  
# Backend container
  backend:
    image: chinmayarvind/aivaluate-backend-quantum-phoenix
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      POSTGRES_DB: AIvaluatedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db

# ollama container
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Ensure Nvidia GPU devices are visible if using GPU
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  ollama_data:

