version: '3.8'
services:
  # frontend:
  #   image: coltonpalfrey/aivaluate-frontend-quantum-phoenix:dev
  #   container_name: frontend_js
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./aivaluate/frontend:/app
  #   command: ["npm", "run", "dev"]

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: database
    environment:
      POSTGRES_DB: AIvaluatedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./aivaluate/database:/docker-entrypoint-initdb.d

# A database manager can be accessed at http://localhost:8080/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # backend:
  #   image: chinmayarvind/ai-valuate-backend-quantum-phoenix:dev
  #   container_name: backend
  #   ports:
  #   - "4000:4000"
  #   depends_on:
  #   - db
  #   env_file:
  #   - ./aivaluate/backend/.env

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80

