version: '3.8'
services:
  frontend:
    build:
      context: ./aivaluate/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: database
    environment:
      POSTGRES_DB: AIvaluatedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./aivaluate/database:/docker-entrypoint-initdb.d

# A database manager can be accessed at http://localhost:8080/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build:
      context: ./aivaluate/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
    - "4000:4000"
    depends_on:
    - db
    env_file:
    - ./aivaluate/backend/.env